apiVersion: tf.galleybytes.com/v1beta1
kind: Terraform
metadata: # kpt-merge: tf-system/example-cluster
  name: controlplane-cluster # kpt-set: ${tf-cluster-name}
  namespace: tf-system
  annotations:
    internal.kpt.dev/upstream-identifier: 'tf.galleybytes.com|Terraform|tf-system|example-cluster'
spec:
  terraformVersion: v1.5.5
  images:
    terraform:
      image: ghcr.io/infinitydon/tf-operator-awscli
  writeOutputsToStatus: true
  outputsSecret: controlplane-cluster-tf-output # kpt-set: ${tf-secret-output-name}
  credentials:
  - aws:
      irsa: arn:aws:iam::989405826384:role/mgmt-argocd-terraform-runner
  terraformModule:
    source: https://github.com/infinitydon/eks-infra-terraform.git//workload-eks-tf-module-github-argocd?ref=main
  backend: |- # kpt-set: ${tf-backend-config}
    terraform {
      backend "kubernetes" {
        secret_suffix    = "ctrlplane-cluster"
        in_cluster_config  = true
        namespace = "tf-system"
      }
    }
  ignoreDelete: false
  keepLatestPodsOnly: true
  persistentVolumeSize: 20Gi
  taskOptions:
  - for:
    - '*'
    env:
    - name: _REVISION
      value: "10"
    - name: TF_VAR_region
      value: us-west-2 # kpt-set: ${aws-region}
    - name: TF_VAR_eks_cluster_name
      value: ctrlplane # kpt-set: ${eks-cluster-name}
    - name: TF_VAR_eks_cluster_version
      value: '"1.31"' # kpt-set: ${eks-version}
    - name: TF_VAR_node_instance_type
      value: m5.4xlarge # kpt-set: ${instance-type}
    - name: TF_VAR_parameter_store_name
      value: control-plane-5g # kpt-set: ${parameter-store-name}
