apiVersion: tf.galleybytes.com/v1beta1
kind: Terraform
metadata: # kpt-merge: tf-system/day0-infra
  name: day0-infra
  namespace: tf-system
  annotations:
    internal.kpt.dev/upstream-identifier: 'tf.galleybytes.com|Terraform|tf-system|day0-infra'
spec:
  terraformVersion: 1.5.5
  writeOutputsToStatus: true
  outputsSecret: day0-infra-outputs
  credentials:
  - aws:
      irsa: IRSA_ARN
  terraformModule:
    source: https://github.com/infinitydon/eks-infra-terraform.git//tgw-vpc-subnet-nat-terraform?ref=main
  backend: |-
    terraform {
      backend "kubernetes" {
        secret_suffix    = "day0-infra"
        in_cluster_config  = true
        namespace = "tf-system"
      }
    }
  ignoreDelete: false
  keepLatestPodsOnly: true
  taskOptions:
  - for:
    - '*' # The following config affects all task pods
    envFrom:
    - secretRef:
        name: GITHUB_PAT_CREDENTIALS # kpt-set: ${github-pat-secret-name}
    env:
    - name: TF_VAR_github_org
      value: GITHUB_ORG # kpt-set: ${github-org}
    - name: TF_VAR_region
      value: DEPLOYMENT_REGION # kpt-set: ${deployment-region}
    - name: TF_VAR_workload_cluster_region
      value: DEPLOYMENT_REGION # kpt-set: ${deployment-region}
    - name: TF_VAR_ran_az1
      value: WORKLOAD_RAN_AZ1 # kpt-set: ${workload-ran-az1}
    - name: TF_VAR_ran_az2
      value: WORKLOAD_RAN_AZ2 # kpt-set: ${workload-ran-az2}
    - name: TF_VAR_core_controlplane_az1
      value: WORKLOAD_CORE_CONTROL_PLANE_AZ1 # kpt-set: ${workload-core-controlplane-az1}
    - name: TF_VAR_core_controlplane_az2
      value: WORKLOAD_CORE_CONTROL_PLANE_AZ2 # kpt-set: ${workload-core-controlplane-az2}
    - name: TF_VAR_core_userplane_az1
      value: WORKLOAD_CORE_USER_PLANE_AZ1 # kpt-set: ${workload-core-userplane-az1}
    - name: TF_VAR_core_userplane_az2
      value: WORKLOAD_CORE_USER_PLANE_AZ2 # kpt-set: ${workload-core-userplane-az2}
    - name: TF_VAR_attach_2nd_eni_lambda_s3_bucket
      value: MULTUS_LAMBDA_S3_BUCKET # kpt-set: ${multus-lambda-s3-bucket}
    - name: TF_VAR_github_repositories
      value: GITHUB_REPOS # kpt-set: ${github-repos}
